version: '3.8'
name: expense-tracker
services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - 80:80

  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - 3000:3000
