# Generated by Django 4.2 on 2023-04-21 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_asset_class', models.BooleanField()),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('opening_date', models.DateField()),
                ('starting_balance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('latest_balance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('default_currency', models.CharField(max_length=3)),
                ('created_on', models.DateField(auto_now_add=True)),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.accounttype')),
            ],
        ),
    ]
