# Generated by Django 4.2 on 2023-04-23 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='latest_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='starting_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
